export const business = { name:'SN Brasil Contábil', phone:'(11) 5611-3549', phone2:'(11) 5614-2142', whatsapp:'(11) 99427-5418', whatsappNumber:'5511994275418', email:'snb@snbrasilcontabil.com.br', address:'Rua Constantino Sérgio, 206', neighborhood:'Jardim Palmares, São Paulo', cep:'04457-140' };

export const services = [
 {slug:'contabilidade',ctaLabel:'Quero cuidar da contabilidade',contactMessage:'Quero conhecer o atendimento contábil para a minha empresa.',title:'Contabilidade e assessoria',short:'Contabilidade',icon:'BookOpen',description:'Organização das informações e acompanhamento da rotina contábil da sua empresa.',headline:'As contas da empresa merecem atenção de perto.',intro:'A contabilidade reúne informações importantes sobre o seu negócio. Nosso trabalho é organizar essa rotina e ajudar você a entender o que os números mostram.',audience:'Para empresas que precisam de acompanhamento contábil e de orientação ao longo da sua operação.',includes:['Organização e escrituração contábil','Preparação de demonstrativos','Acompanhamento da rotina da empresa','Assessoria para dúvidas do dia a dia'],question:'Posso conversar com vocês se já tenho um contador?',answer:'Pode, sim. Conte como funciona o atendimento atual e o que você está procurando. A equipe pode orientar sobre uma possível mudança e os documentos necessários.'},
 {slug:'abertura-de-empresa',ctaLabel:'Quero abrir minha empresa',contactMessage:'Quero abrir minha empresa e preciso de orientação para começar.',title:'Abertura de empresa',short:'Abertura de empresa',icon:'Building2',description:'Orientação para tirar o negócio do papel e organizar os primeiros passos.',headline:'Vamos tirar a sua empresa do papel.',intro:'Você tem uma ideia de negócio e precisa entender por onde começar. A gente ajuda a organizar a abertura, as informações e os documentos necessários para cada etapa.',audience:'Para quem está começando um negócio e quer orientação para formalizar a empresa.',includes:['Entendimento das atividades do negócio','Orientação sobre documentos e registros','Acompanhamento das etapas de abertura','Organização da rotina contábil inicial'],question:'Preciso ter todos os documentos para falar com vocês?',answer:'Não precisa. A primeira conversa serve para entender o que você pretende fazer e quais informações precisam ser reunidas. Traga suas dúvidas também.'},
 {slug:'fiscal-e-tributario',ctaLabel:'Quero organizar a parte fiscal',contactMessage:'Preciso de ajuda com as obrigações fiscais da minha empresa.',title:'Fiscal e tributário',short:'Fiscal e tributário',icon:'ReceiptText',description:'Acompanhamento das obrigações fiscais e orientação sobre a realidade do negócio.',headline:'Uma rotina fiscal bem acompanhada.',intro:'Impostos, documentos fiscais e declarações fazem parte da rotina de uma empresa. A SN Brasil acompanha essas obrigações e orienta sobre as particularidades de cada atividade.',audience:'Para empresas que precisam organizar suas obrigações fiscais e esclarecer questões tributárias.',includes:['Acompanhamento de obrigações fiscais','Organização de documentos e informações','Assessoria tributária','Orientação sobre declarações e apurações'],question:'Vocês analisam a situação específica da minha empresa?',answer:'Sim. A atividade, a documentação e a forma de operação precisam ser entendidas antes de definir o atendimento. Conte para a equipe qual é a sua necessidade.'},
 {slug:'departamento-pessoal',ctaLabel:'Preciso de apoio com a folha',contactMessage:'Preciso de apoio com a folha de pagamento e as rotinas da equipe.',title:'Departamento pessoal',short:'Departamento pessoal',icon:'Users',description:'Apoio nas rotinas de folha e nas obrigações relacionadas à equipe.',headline:'Cuidado com a rotina de quem trabalha com você.',intro:'Admissões, folha, férias e desligamentos pedem organização. A gente acompanha as rotinas do departamento pessoal para que as informações da equipe sejam tratadas com atenção.',audience:'Para empresas que têm funcionários ou estão se preparando para contratar.',includes:['Rotinas de admissão e desligamento','Processamento da folha de pagamento','Acompanhamento de férias e informações da equipe','Orientação sobre obrigações do departamento pessoal'],question:'Posso procurar vocês antes de fazer a primeira contratação?',answer:'Sim. Conversar antes ajuda a conhecer as etapas e reunir as informações necessárias. Explique como pretende organizar a equipe e o atendimento será orientado a partir disso.'},
 {slug:'regularizacao-e-encerramento',ctaLabel:'Quero verificar meu CNPJ',contactMessage:'Preciso de orientação para regularizar ou encerrar uma empresa.',title:'Regularização e encerramento',short:'Regularização e encerramento',icon:'FolderCheck',description:'Análise de pendências e orientação para regularizar ou encerrar a empresa.',headline:'Vamos entender o que precisa ser colocado em ordem.',intro:'Se existe uma pendência ou você precisa encerrar uma empresa, o primeiro passo é conhecer a situação. A equipe acompanha a análise e orienta sobre as etapas necessárias.',audience:'Para quem precisa verificar pendências, regularizar o CNPJ ou cuidar do encerramento de uma empresa.',includes:['Levantamento da situação da empresa','Orientação sobre pendências identificadas','Acompanhamento da regularização','Orientação e acompanhamento do encerramento'],question:'A empresa está sem movimento. Ainda preciso verificar a situação?',answer:'Vale conversar com a equipe e apresentar o CNPJ. A análise das informações permite entender a situação e orientar quais providências precisam ser avaliadas.'},
 {slug:'certificado-digital',ctaLabel:'Preciso de certificado digital',contactMessage:'Preciso de um certificado digital e quero entender qual atende ao meu caso.',title:'Certificado digital',short:'Certificado digital',icon:'Fingerprint',description:'Orientação para escolher e utilizar o certificado adequado à sua necessidade.',headline:'O certificado certo para o que você precisa fazer.',intro:'O certificado digital é usado para identificar e assinar em ambientes eletrônicos. A SN Brasil ajuda a entender a sua necessidade e orienta o atendimento relacionado ao certificado.',audience:'Para pessoas e empresas que precisam de orientação sobre certificado digital.',includes:['Entendimento da finalidade do certificado','Orientação sobre as opções de atendimento','Informações sobre documentação','Apoio nas dúvidas de uso e renovação'],question:'Como sei qual certificado preciso?',answer:'Conte onde você pretende utilizá-lo e se o atendimento é para pessoa física ou empresa. Com essas informações, a equipe orienta os próximos passos.'},
 {slug:'creditos-tributarios',ctaLabel:'Quero avaliar possíveis créditos',contactMessage:'Quero avaliar possíveis créditos tributários da minha empresa.',title:'Créditos tributários',short:'Créditos tributários',icon:'FileSearch',description:'Análise das informações para verificar possíveis créditos da empresa.',headline:'Uma análise cuidadosa das informações tributárias.',intro:'A verificação de créditos tributários começa pela documentação e pela realidade de cada empresa. A equipe analisa as informações para identificar o que pode ser avaliado no seu caso.',audience:'Para empresas que querem avaliar possíveis créditos tributários com base em sua documentação.',includes:['Levantamento de informações tributárias','Análise dos documentos apresentados','Verificação de possíveis créditos','Orientação sobre os resultados da análise'],question:'Toda empresa tem créditos a recuperar?',answer:'Isso depende da situação e da documentação. A análise é necessária para verificar se existem oportunidades no caso da sua empresa, sem antecipar um resultado.'},
 {slug:'aposentadoria',ctaLabel:'Quero falar sobre aposentadoria',contactMessage:'Quero entender meu tempo de contribuição e a orientação para aposentadoria.',title:'Orientação para aposentadoria',short:'Aposentadoria',icon:'Clock3',description:'Análise do tempo de contribuição e orientação sobre o requerimento.',headline:'Planejar o próximo passo com orientação.',intro:'Entender o histórico de contribuição ajuda a organizar o planejamento. A SN Brasil oferece atendimento para contagem do tempo de contribuição e orientação sobre o requerimento administrativo.',audience:'Para quem precisa entender seu tempo de contribuição e organizar as informações para o atendimento.',includes:['Levantamento do histórico de contribuição','Contagem do tempo de contribuição','Orientação sobre informações e documentos','Acompanhamento do requerimento administrativo'],question:'Como começo esse atendimento?',answer:'Entre em contato e conte o que você quer verificar. A equipe orienta quais informações serão necessárias para conhecer seu histórico e avaliar o caso.'},
];

export const sectors = [
 {name:'Engenharia',label:'Projetos e serviços técnicos',text:'Contratos, prestação de serviços e organização das informações de cada projeto. Uma rotina que pede atenção às particularidades da atividade.',icon:'Ruler'},
 {name:'Construção',label:'Obras e operação',text:'Documentos, equipe e acompanhamento das atividades da empresa. A contabilidade precisa considerar a forma como o negócio funciona.',icon:'HardHat'},
 {name:'Máquinas e empilhadeiras',label:'Equipamentos e serviços',text:'Comércio, locação ou prestação de serviços têm rotinas diferentes. O atendimento começa por conhecer a operação e as suas necessidades.',icon:'Cog'},
 {name:'Eventos',label:'Produção e prestação de serviços',text:'Organização das informações de contratos, fornecedores e equipe para acompanhar a movimentação do negócio.',icon:'CalendarDays'},
 {name:'Indústria',label:'Produção e atividade empresarial',text:'Acompanhamento contábil e fiscal atento aos documentos e às particularidades da operação industrial.',icon:'Factory'},
 {name:'Outras atividades',label:'Cada empresa tem seu jeito',text:'Seu negócio não está nesta lista? Conte para a equipe o que você faz e quais são as suas dúvidas. A conversa é o primeiro passo.',icon:'BriefcaseBusiness'},
];
export const faq = [
 {q:'Quero abrir uma empresa. Por onde começo?',a:'Comece contando o que você pretende fazer. A equipe ajuda a entender as etapas, as informações e os documentos que precisam ser reunidos para a abertura.'},
 {q:'Já tenho uma empresa. Posso mudar de contabilidade?',a:'Pode conversar com a gente sobre isso. Vamos entender o que você procura e orientar sobre a documentação e a organização de uma possível mudança.'},
 {q:'Preciso falar sobre uma pendência no CNPJ.',a:'Entre em contato e conte o que você já sabe sobre a situação. A análise das informações é o caminho para entender a pendência e orientar o atendimento.'},
 {q:'Como solicito uma proposta de atendimento?',a:'Use o WhatsApp, o telefone ou o formulário de contato. Conte a atividade da empresa e o que você precisa. A proposta depende do escopo do atendimento.'},
];
